// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/ziv_l/Desktop/file/projects/classroom-mg-sys/node_modules/.store/@ant-design+icons@4.8.3/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import AuditOutlined from '/Users/ziv_l/Desktop/file/projects/classroom-mg-sys/node_modules/.store/@ant-design+icons@4.8.3/node_modules/@ant-design/icons/es/icons/AuditOutlined';
import BankOutlined from '/Users/ziv_l/Desktop/file/projects/classroom-mg-sys/node_modules/.store/@ant-design+icons@4.8.3/node_modules/@ant-design/icons/es/icons/BankOutlined';
import FileDoneOutlined from '/Users/ziv_l/Desktop/file/projects/classroom-mg-sys/node_modules/.store/@ant-design+icons@4.8.3/node_modules/@ant-design/icons/es/icons/FileDoneOutlined';
import UserOutlined from '/Users/ziv_l/Desktop/file/projects/classroom-mg-sys/node_modules/.store/@ant-design+icons@4.8.3/node_modules/@ant-design/icons/es/icons/UserOutlined';
import SettingOutlined from '/Users/ziv_l/Desktop/file/projects/classroom-mg-sys/node_modules/.store/@ant-design+icons@4.8.3/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { DashboardOutlined, AuditOutlined, BankOutlined, FileDoneOutlined, UserOutlined, SettingOutlined };
