// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"name":"login","path":"/login","layout":false,"id":"1"},"2":{"name":"register","path":"/register","layout":false,"id":"2"},"3":{"name":"数据统计","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"预约审核","path":"/applyAudit","icon":"AuditOutlined","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"教室信息","path":"/classroomInfo","icon":"BankOutlined","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"管理员注册审核","path":"/teacherAudit","icon":"FileDoneOutlined","access":"isAdmin","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"个人中心","path":"/account","icon":"UserOutlined","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"系统配置","path":"/config","access":"isAdmin","icon":"SettingOutlined","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"*","layout":false,"id":"9"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__ApplyAudit__index" */'@/pages/ApplyAudit/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__ClassroomInfo__index" */'@/pages/ClassroomInfo/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__TeacherAudit__index" */'@/pages/TeacherAudit/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Account__index" */'@/pages/Account/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Config__index" */'@/pages/Config/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/ziv_l/Desktop/file/projects/classroom-mg-sys/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
